### ISSUE TITLE
Files: where are the datafiles for exercises?

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/fopp#64]
The exercises mention several data files -- where can the students view those?

@laumurph

**Comment by laumurph** [comment]
When we wrote questions using these files originally we didn't have a space for students to view the files (possibly because the files are short and students could just print them out.) We could display them in an earlier chapter, though some of the data files go by different names, even though they have the same content, because of warnings that pop up about duplicate ids. That could become confusing for students if they see the same data being called different names.

**Comment by bnmnetp** [comment]
We should definitely be consistent in what we call a file, especially now that the file open and read operations will work regardless of whether the datafile directive is on the same page.

So we could even put them on the Exercises page - outside of the activecode directive - so the student can see them, and do the work without hitting the database.

**Comment by laumurph** [comment]
So I should be able to define a datafile on one page (say the exercises page) and open/read it on a separate page (say the chapter assessment page)? Does the datafile need anything special added to work?

**Comment by bnmnetp** [comment]
No, it just needs to use the same id consistently -- when we build the book we put the contents of the 'file' in the database and then at runtime the more recent versions of runestone will look for the file on the page first, but if its not found then it will make a an API call to get it from the DB.
